---
- hosts: local
  connection: local
  become: yes
  become_user: root
  tasks:
   - name: Install git
     apt:
       name: nginx
       state: installed
       update_cache: true

   - name: Install jdk
     apt:
       name: nginx
       state: installed
       update_cache: true

  - name: Install java 8 preresequesits
    apt: name=python-software-properties

  - name: Add Java 8 repository
    apt_repository: repo='ppa:webupd8team/java'

  - name: Agree to oracle license
    debconf: name=oracle-java8-installer question=shared/accepted-oracle-license-v1-1 vtype=select value=true

  - name: Install Java 8
    apt: 
       name=oracle-java8-installer 
       force=yes

- name: Create /opt/src
  file: path=/opt/src state=directory recurse=yes

- name: Create lib dir
  file: path={{sbt_lib_path_target}} state=directory recurse=yes

- name: Download sbt v{{sbt_version}}
  get_url: url={{sbt_download_url}} 
    dest=/opt/src/{{sbt_archive_file}}

- name: Unpack sbt
  unarchive: src=/opt/src/{{sbt_archive_file}} dest={{sbt_lib_path_target}} copy=no

- name: Link sbt
  file: state=link src={{sbt_lib_path_target}}/sbt/bin/sbt dest={{sbt_link_target}}


   - name: Install docker
     apt:
       name: nginx
       state: installed
       update_cache: true
